#!/usr/bin/env python3
"""The revision ledger: where each lesson stands in the /prepare pass, measured, never flipped by hand.

    python3 _tooling/ledger.py            # prove every fence, lint every lesson, write the ledger
    python3 _tooling/ledger.py --no-run   # skip prove.py (the proofs column reads "—")
    python3 _tooling/ledger.py --next     # print the next lesson to prepare, in book order

A lesson is DONE when its proofs pass, its session record has a gaps table, a fact-check and a
review at the floor, and prepare_lint.py finds nothing. Writes `_prepare/revision-ledger.md`.
"""
from __future__ import annotations

import contextlib
import io
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import prepare_lint  # noqa: E402
import prove  # noqa: E402

ROOT = prove.ROOT
OUT = ROOT / "_prepare" / "revision-ledger.md"


def filled_rows(record: str, name: str) -> int:
    rows = [l for l in prepare_lint.subsection(record, name).splitlines()
            if l.strip().startswith("|") and not re.match(r"^\|\s*(-|Gap|Claim|Section|Criterion)", l.strip())]
    return sum(1 for r in rows if any(c.strip() for c in r.strip().strip("|").split("|")))


def row(lesson: Path, run: bool) -> dict:
    record_file = prepare_lint.record_path(lesson)
    record = record_file.read_text(encoding="utf-8") if record_file.exists() else ""
    if run:
        fences = [prove.prove(f) for f in prove.parse(lesson)]
        good = sum(f.status in prove.GOOD for f in fences)
        proofs = f"{good}/{len(fences)}"
        proofs_ok = good == len(fences)
    else:
        proofs, proofs_ok = "—", True
    with contextlib.redirect_stdout(io.StringIO()):
        problems = prepare_lint.lint(lesson, run=False, quiet=True)
    review = prepare_lint.review_problems(record) if record else ["none"]
    gaps, facts = filled_rows(record, "Gaps in the chapter"), filled_rows(record, "Fact-check")
    done = proofs_ok and record and gaps and facts and not review and problems == 0
    return {"lesson": str(lesson.relative_to(ROOT)), "proofs": proofs, "gaps": gaps or "—",
            "fact": facts or "—", "review": "pass" if not review else ("—" if not record else "below 4"),
            "lint": problems, "state": "DONE" if done else "TODO"}


def main(argv: list[str]) -> int:
    lessons = [l for l in prove.lessons([]) if not l.name.endswith("00-index.md")]
    if "--next" in argv:
        for lesson in lessons:
            if row(lesson, run=False)["state"] != "DONE":
                print(lesson.relative_to(ROOT))
                return 0
        print("every lesson is DONE")
        return 0
    rows = [row(l, run="--no-run" not in argv) for l in lessons]
    done = sum(r["state"] == "DONE" for r in rows)
    lines = [
        "# Revision ledger — the /prepare pass",
        "",
        "Generated by `python3 _tooling/ledger.py`; do not edit by hand. Proofs = `prove.py`, lint =",
        "`prepare_lint.py` problem count, gaps and fact-check = filled rows in the lesson's",
        "`_<stem>.session.md`, review = every criterion ≥ 4 after the fix.",
        "",
        f"**{done} of {len(rows)} lessons DONE.**",
        "",
        "| Lesson | Proofs | Gaps | Fact-check | Review | Lint | State |",
        "|---|---|---|---|---|---|---|",
    ]
    lines += [f"| `{r['lesson']}` | {r['proofs']} | {r['gaps']} | {r['fact']} | {r['review']} | {r['lint']} | {r['state']} |"
              for r in rows]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {done}/{len(rows)} DONE")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
